language: python
cache:
    pip: true

install:
  - pip install tox

script:
  - tox

matrix:
  include:
    - { python: 2.7, env: TOXENV=py27 }
    - { python: 3.4, env: TOXENV=py34 }
    - { python: 3.5, env: TOXENV=py35 }
    - { python: 3.6, env: TOXENV=py36 }
    - { python: 3.7-dev, env: TOXENV=py37 }
    - { python: 3.6, env: TOXENV=docs }
    - { python: 3.6, env: TOXENV=flake8 }
    - { python: 3.6, env: TOXENV=isort }
    - { python: 3.6, env: TOXENV=black }
